### ISSUE TITLE
implement class containing file sharing methods

### ISSUE THREAD

**Issue by vaibhav604** [tarunKoyalwar/Ftp-over-UDP#4]
We need to implement class which contains two methods : writer and reader method.

1.  Reader method will read byte data chunk by chunk to send it to receiver.
2.  And writer method will combine all received packets.

**Comment by aksy007** [comment]
import java.io.*;
import java.util.Scanner;
public class fileshare
{
  public void reader_method()
  {
    try(BufferedInputStream in = new BufferedInputStream(new FileInputStream(pathname)))   // pathname of file which you wish to send
    {
      byte[] bbuf = new byte[1024];
      int len;
      while ((len = in.read(bbuf)) != -1)
        {
        // process buff here.
        System.out.println(len);
        System.out.println("pause");

        }

    }
    catch (IOException ex)
    {
      ex.printStackTrace();
    }
  }

  //write method-----------------------------------------------------------------------
  public void writer_method()
  {
    try(BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream(pathname)))  // pathname of file
    {
      //process buff here.
      byte b=23;
      out.write(b);

    }
    catch (FileNotFoundException fnfe)
    {
      System.out.println("File not found" + fnfe);
    }
    catch (IOException ioe)
    {
      System.out.println("Error while writing to file" + ioe);
    }
  }
}
